### ISSUE TITLE
Meteor: 'error: no such package'

### ISSUE THREAD

**Issue by rohundhar** [vurankar/meteor-accounts-okta#2]
Hi there! I would love to use this package for something I am working on, but when I ran the meteor add command I received this error: 

```
rohundhar:testApp rohun.dhar$ meteor add vurankar:accounts-okta
 => Errors while parsing arguments:           
                                              
While adding package vurankar:accounts-okta:
error: no such package
```

Is there any way to use this package through meteor, either through meteor add or by forking and packaging it myself?

**Comment by developeron29** [comment]
+1

**Comment by rohundhar** [comment]
Going to close this issue out because I ended up forking my own repo and got it working.
